inherit_from: .rubocop_todo.yml

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
